
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface CircuitSym {
  /* terminals */
  public static final int CHAR_CONST = 45;
  public static final int LGPAR = 16;
  public static final int CHAR = 27;
  public static final int GE = 35;
  public static final int UMINUS = 33;
  public static final int DOUBLE_CONST = 43;
  public static final int DOUBLE = 25;
  public static final int SEMI = 12;
  public static final int INT = 23;
  public static final int OUT = 6;
  public static final int MINUS = 29;
  public static final int WRITE = 11;
  public static final int INOUT = 7;
  public static final int AND = 40;
  public static final int NOT = 39;
  public static final int LT = 36;
  public static final int RPAR = 15;
  public static final int OR = 41;
  public static final int IN = 5;
  public static final int RGPAR = 17;
  public static final int BOOL = 24;
  public static final int COMMA = 13;
  public static final int DIV = 31;
  public static final int PLUS = 28;
  public static final int ASSIGN = 32;
  public static final int IF = 18;
  public static final int ID = 46;
  public static final int LE = 37;
  public static final int EOF = 0;
  public static final int INT_CONST = 42;
  public static final int TRUE = 8;
  public static final int error = 1;
  public static final int START = 3;
  public static final int EQ = 38;
  public static final int HEAD = 2;
  public static final int TIMES = 30;
  public static final int ELSE = 22;
  public static final int READ = 10;
  public static final int WHILE = 20;
  public static final int THEN = 19;
  public static final int LPAR = 14;
  public static final int STRING = 26;
  public static final int DEF = 4;
  public static final int FALSE = 9;
  public static final int STRING_CONST = 44;
  public static final int GT = 34;
  public static final int DO = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "HEAD",
  "START",
  "DEF",
  "IN",
  "OUT",
  "INOUT",
  "TRUE",
  "FALSE",
  "READ",
  "WRITE",
  "SEMI",
  "COMMA",
  "LPAR",
  "RPAR",
  "LGPAR",
  "RGPAR",
  "IF",
  "THEN",
  "WHILE",
  "DO",
  "ELSE",
  "INT",
  "BOOL",
  "DOUBLE",
  "STRING",
  "CHAR",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "ASSIGN",
  "UMINUS",
  "GT",
  "GE",
  "LT",
  "LE",
  "EQ",
  "NOT",
  "AND",
  "OR",
  "INT_CONST",
  "DOUBLE_CONST",
  "STRING_CONST",
  "CHAR_CONST",
  "ID"
  };
}

